# Generated by Django 4.1.7 on 2023-12-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('opis', models.TextField(blank=True, null=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ilosc', models.PositiveIntegerField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zamowienia', models.DateTimeField(auto_now_add=True)),
                ('cena_koncowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.klient')),
            ],
        ),
        migrations.CreateModel(
            name='ZamowienieProdukt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilosc', models.PositiveIntegerField()),
                ('cena_produktu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produkt')),
                ('zamowienie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zamowienie')),
            ],
        ),
        migrations.AddField(
            model_name='zamowienie',
            name='produkty',
            field=models.ManyToManyField(through='app.ZamowienieProdukt', to='app.produkt'),
        ),
    ]
