# Generated by Django 4.1.7 on 2023-12-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='cena_koncowa',
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='produkty',
            field=models.ManyToManyField(to='app.produkt'),
        ),
        migrations.DeleteModel(
            name='ZamowienieProdukt',
        ),
    ]
