# Generated by Django 4.1.7 on 2023-12-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_zamowienie_cena_koncowa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zamowienie',
            name='produkty',
        ),
    ]
