# Generated by Django 4.1.7 on 2023-12-08 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_zamowienie_produkty'),
    ]

    operations = [
        migrations.AddField(
            model_name='zamowienie',
            name='produkt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.produkt'),
        ),
    ]
