# Generated by Django 4.1.7 on 2023-12-08 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_zamowienie_produkt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zamowienie',
        ),
    ]
