# Generated by Django 4.1.7 on 2023-12-11 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='klient',
            managers=[
            ],
        ),
    ]
